#!/bin/bash

LOCKFILE=/tmp/git-bkradd.lock

function bye() {
  if [ -x "$( type -p zenity )" ]; then
    zenity --error --text "$1"
  else
    echo "ERROR: $1" >&2
  fi
  exit 1
}

while true; do
  if [ ! -e $LOCKFILE ]; then
    break
  fi
  if ! ps $( cat $LOCKFILE ) >/dev/null; then
    rm $LOCKFILE || bye "LOCKFILE with incorrect pid cleanup failed"
    break
  fi
  echo -n '.'
  sleep 3
done

echo $$ >$LOCKFILE || bye "LOCKFILE creation failed"
trap "rm $LOCKFILE" EXIT

[ -r Makefile -a -r runtest.sh ] || bye "'Makefile' or 'runtest.sh' is missing in current directory. Is this a Beaker test?"
[ -r /usr/share/rhts/lib/rhts-make.include ] || bye "File '/usr/share/rhts/lib/rhts-make.include' not available. Maybe package 'rhts-devel' is not installed?"
git pull --rebase || bye "'git pull --rebase' failed in $( pwd )"
git pull --tags || bye "'git pull --tags' failed in $( pwd )"
git push || bye "'git push' failed in $( pwd )"
make tag || bye "'make tag' failed in $( pwd )"
git push --tags || bye "'git push --tags' failed in $( pwd )"
make bkradd || bye "'make bkradd' failed in $( pwd )"
