#!/bin/bash

set -e

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
  echo "ERROR: Some of the options is empty" >&2
  exit 1
fi

echo "Task ID: $1"
echo "     annotation: $2"
echo "     wait: $3"

set -x

task $1 annotate "$2"
task $1 modify wait:$3
